import { CardSuite } from './card-suite'

export const deck = [
  // Clovers
  { suite: CardSuite.Clovers, value: 'ace' },
  { suite: CardSuite.Clovers, value: 'two' },
  { suite: CardSuite.Clovers, value: 'three' },
  { suite: CardSuite.Clovers, value: 'four' },
  { suite: CardSuite.Clovers, value: 'five' },
  { suite: CardSuite.Clovers, value: 'six' },
  { suite: CardSuite.Clovers, value: 'seven' },
  { suite: CardSuite.Clovers, value: 'eight' },
  { suite: CardSuite.Clovers, value: 'nine' },
  { suite: CardSuite.Clovers, value: 'ten' },
  { suite: CardSuite.Clovers, value: 'jack' },
  { suite: CardSuite.Clovers, value: 'queen' },
  { suite: CardSuite.Clovers, value: 'king' },
  // Hearts
  { suite: CardSuite.Hearts, value: 'ace' },
  { suite: CardSuite.Hearts, value: 'two' },
  { suite: CardSuite.Hearts, value: 'three' },
  { suite: CardSuite.Hearts, value: 'four' },
  { suite: CardSuite.Hearts, value: 'five' },
  { suite: CardSuite.Hearts, value: 'six' },
  { suite: CardSuite.Hearts, value: 'seven' },
  { suite: CardSuite.Hearts, value: 'eight' },
  { suite: CardSuite.Hearts, value: 'nine' },
  { suite: CardSuite.Hearts, value: 'ten' },
  { suite: CardSuite.Hearts, value: 'jack' },
  { suite: CardSuite.Hearts, value: 'queen' },
  { suite: CardSuite.Hearts, value: 'king' },
  // Pikes
  { suite: CardSuite.Pikes, value: 'ace' },
  { suite: CardSuite.Pikes, value: 'two' },
  { suite: CardSuite.Pikes, value: 'three' },
  { suite: CardSuite.Pikes, value: 'four' },
  { suite: CardSuite.Pikes, value: 'five' },
  { suite: CardSuite.Pikes, value: 'six' },
  { suite: CardSuite.Pikes, value: 'seven' },
  { suite: CardSuite.Pikes, value: 'eight' },
  { suite: CardSuite.Pikes, value: 'nine' },
  { suite: CardSuite.Pikes, value: 'ten' },
  { suite: CardSuite.Pikes, value: 'jack' },
  { suite: CardSuite.Pikes, value: 'queen' },
  { suite: CardSuite.Pikes, value: 'king' },
  // Tiles
  { suite: CardSuite.Tiles, value: 'ace' },
  { suite: CardSuite.Tiles, value: 'two' },
  { suite: CardSuite.Tiles, value: 'three' },
  { suite: CardSuite.Tiles, value: 'four' },
  { suite: CardSuite.Tiles, value: 'five' },
  { suite: CardSuite.Tiles, value: 'six' },
  { suite: CardSuite.Tiles, value: 'seven' },
  { suite: CardSuite.Tiles, value: 'eight' },
  { suite: CardSuite.Tiles, value: 'nine' },
  { suite: CardSuite.Tiles, value: 'ten' },
  { suite: CardSuite.Tiles, value: 'jack' },
  { suite: CardSuite.Tiles, value: 'queen' },
  { suite: CardSuite.Tiles, value: 'king' },
  // Jokers
  { suite: CardSuite.Jokers, value: 'joker' },
  { suite: CardSuite.Jokers, value: 'joker' },
]
